# Generated by Django 4.1.2 on 2022-10-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pass1',
            new_name='password',
        ),
    ]
