# Generated by Django 4.1.2 on 2022-10-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_rename_pass1_student_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
