# Generated by Django 4.1.2 on 2022-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
