# Generated by Django 4.1.2 on 2022-10-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_delete_test_alter_students_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
